service: myService

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

functions:
  overviewCrawl:
    handler: handlers/indexLambdaFlow.handleEvent
    name: ${self:provider.stage}-overviewCrawl
    timeout: 300
    memorySize: 512
    events:
      - sqs:
          arn: ${self:custom.queues.z_menu_promo_queue_arn.${self:provider.stage}}
          batchSize: 1